services:
  talents_school_api:
    image: ${DOCKER_REGISTRY-}talentsschoolapi
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      talents_school_db:
        condition: service_healthy
    networks:
      - talents_school_net

  talents_school_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: talents_school_db
    networks:
      - talents_school_net
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyPass*123456
    ports:
      - 1433:1433
    volumes:
      - ./SQL-Server/data:/var/opt/mssql/data
      - ./SQL-Server/log:/var/opt/mssql/log
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "MyPass*123456", "-Q", "SELECT 1", "-C"]
      interval: 5s
      timeout: 3s
      retries: 30 

networks:  
  talents_school_net:
    name: talents_school_net
    driver: bridge
